mysql> CREATE TABLE film(
    -> id INT PRIMARY KEY,
    -> nom VARCHAR(50),
    -> affiche VARCHAR(50),
    -> description VARCHAR(1000),
    -> genre VARCHAR(50),
    -> CHECK(genre IN ('Comédie','Drame','Thriller','Action','Horreur','Science-fiction','Fantastique','Animation','Documentaire','Guerre','Western'),
    -> l_real VARCHAR(100),
    -> l_act VARCHAR(100)
    ->An_Sortie int
    ->film_vu BOOLEAN
    ->duree TIME);


mysql> CREATE TABLE personne(
    -> id INT PRIMARY KEY,
    -> prenom VARCHAR(50),
    -> nom VARCHAR(50),
    -> anNais INT,
    -> description VARCHAR(1000),
    -> photo VARCHAR(50),
    -> metier VARCHAR(50),
    -> CHECK( metier IN ('réalisateur','acteur','act_réal')),
    -> l_film VARCHAR(100));

mysql> INSERT INTO personne(id,prenom,nom,anNais,description,photo,metier,l_film) VALUES(0,'Sylvester','Stallone',1946,"Sylvester Stallone, né le 6 juillet 1946 à New York, est un acteur, réalisateur, scénariste et producteur américain d'origine italienne, ukrainienne et française. Son rôle emblématique dans 'Rocky' en 1976 lui vaut nominations et succès. Il incarne également John Rambo en 1982, déclenchant une série de films à succès. Il s'illustre dans les années 1980 avec des productions à gros budget comme 'Tango et Cash', 'Cliffhanger' et 'Demolition Man'. Ses genres de prédilection sont l'action et le drame, avec des films comme 'Copland' en 1997. En 2016, il remporte un Golden Globe pour 'Creed'. Stallone possède son étoile sur le Hollywood Walk of Fame depuis 1984.",'../photo/Stallone.png','acteur','0');
mysql> INSERT INTO personne VALUES(1,'Carl','Weathers',1948,"Carl Weathers, né le 14 janvier 1948 à La Nouvelle-Orléans et mort le 2 février 20241 à Los Angeles, est un footballeur, acteur, réalisateur et producteur américain. Apparaissant dans 75 films et émissions de télévision au cours de ses cinquante années de carrière, Carl Weathers est notamment connu pour avoir incarné le rôle du boxeur Apollo Creed dans les quatre premiers films de la saga Rocky (1976-1985) aux côtés de Sylvester Stallone, et celui du major George Dillon dans le film Predator (1987) aux côtés d'Arnold Schwarzenegger. En 2019, il incarne le rôle de Greef Karga dans la série en prise de vues réelles The Mandalorian, issue de l'univers Star Wars. Il est également réalisateur de plusieurs épisodes dans les trois saisons de la série",'../photo/Weathers.png','act_réal','0');
mysql> INSERT INTO personne VALUES(2,'John','Guilbert Avildsen',1935,"John Guilbert Avildsen, dit John G. Avildsen, est un réalisateur, acteur, monteur et producteur américain né le 21 décembre 1935 à Oak Park, en banlieue de Chicago dans l'Illinois, et mort le 16 juin 2017 à Los Angeles. Il était aussi connu sous le nom de Danny Mulroon.",'../photo/Guilbert_Avildsen.png','act_réal','0');
mysql> INSERT INTO film VALUES(0,'Rocky','../affiche/Rocky.png',"L'histoire de Rocky Balboa, un boxeur inconnu. De ses difficultés à son affrontement contre le champion du monde Apollo Creed.",'Drame','2','0,1',1976,false,'01:59:00');
mysql> INSERT INTO personne VALUES(3,'Dwayne','Johnson',1972,"Dwayne Johnson, également connu sous le surnom de The Rockn 2, est un acteur, producteur, catcheur (lutteur professionnel) américano-canadien, né le 2 mai 1972 à Hayward (Californie).Issu d'une famille de lutteurs, il devient lui aussi catcheur. Il devient connu au sein de la World Wrestling Federation / Entertainment jusqu'en 2004 et revient à la compétition de février 2011 à avril 2013 puis fait occasionnellement quelques apparitions.Il commence vers la fin des années 1990 une carrière d'acteur à Hollywood, d'abord en meant à profit sa notoriété précédente et en utilisant son nom de catcheur. Il accède rapidement aux premiers rôles dans les années 2000, devenant une vedette de cinéma à part entière en étant l'acteur principal de nombreux films d'action, jusqu'à devenir l'acteur le mieux payé au monde en 2016 et 2019 selon le magazine Forbes. Il fait aussi partie des cent personnes les plus influentes dans le monde selon le Time 100 de 2016 et 2019",'../photo/Johnson.png','acteur','3');
mysql> INSERT INTO personne VALUES(4,'Vin','Diesel',1967,"Mark Sinclair Vincent, dit Vin Diesel, né le 18 juillet 1967, à Alameda, en Californie est un acteur, chanteur, réalisateur, cascadeur, scénariste et producteur de cinéma américain.Il est révélé par un second rôle dans Il faut sauver le soldat Ryan (1998), avant de devenir la star de plusieurs franchises du cinéma d'action : Les Chroniques de Riddick (2000-2013), Fast and Furious (2001-) et xXx (2002-).Il prête sa voix au Géant de fer dans le film d'animation homonyme (1999) ainsi qu'à Groot dans les œuvres du MCU (2014-) dont le film Les Gardiens de la Galaxie (2014) et ses suites (2017 et 2023)",'../photo/Diesel.png' ,'act_réal','1,3');
mysql> INSERT INTO personne VALUES(5,'Paul','Walker',1973,"Paul Walker, né le 12 septembre 1973 à Glendale en Californie et mort le 30 novembre 2013 à Valencia dans le même État, est un acteur, scénariste et producteur de cinéma américain. Il est principalement connu pour avoir incarné Brian O'Conner dans la saga Fast and Furious",'../photo/Walker.png','acteur','1,2,3');
mysql> INSERT INTO film VALUES(1,'Fast and Furious','../affiche/Fast_and_Furious.jpg',"Dominic Toretto, un ancien prisonnier devenu pilote de courses de rue, dirige une bande qu'il considère comme sa famille, incluant Letty, Vince, Jesse, Leon et sa sœur Mia. Brian O'Conner, sous couverture en tant que Brian Earl Spilner, s'infiltre dans la bande pour enquêter sur des attaques de camions. Il gagne leur confiance en sauvant Dom lors d'une course. Brian tombe amoureux de Mia et, malgré ses sentiments, mène ses collègues sur de fausses pistes pour protéger Dom. Lors d'une attaque de camion, Brian révèle sa véritable identité pour sauver Vince, ce qui met Mia du côté de son frère. Après une confrontation avec une bande rivale, Brian aide Dom à fuir en lui donnant sa voiture, perdant ainsi son insigne de policier",'Action','7','4,5',2001,false,'01:47:00');
mysql> INSERT INTO film VALUES(2,'2 Fast 2 Furious','../affiche/2_Fast_2_Furious.jpg',"Après avoir laissé s'échapper le fugitif Dominic Toretto, l'ancien officier du LAPD Brian O'Conner est, comme Torreto, désormais en cavale et quitte Los Angeles pour Miami, afin de commencer une nouvelle vie. Mais une nuit, il est pris par les agents fédéraux des douanes. Le FBI lui offre une dernière chance : s'il accepte de prendre part à une opération conjointe des douanes et du FBI, son passé criminel sera effacé.Le but de la mission est d'arrêter Carter Verone, un baron de la drogue argentin. Pour le prendre en flagrant délit de blanchiment d'argent, Brian devra faire appel à ses compétences de pilote de rue. Refusant le partenaire que le FBI veut lui adjoindre, il impose la présence d'un ancien ami, Roman Pearce, devenu pilote de demolition derby et assigné à résidence pour des délits commis des années auparavant. Ils seront secondés par la plantureuse Monica Fuentes, « fiancée » de Carter et en fait flic infiltrée depuis longtemps, comme Brian à l'époque de l'affaire Toretto.",'Action','6','4,5',2003,false,'01:47:00');
mysql> INSERT INTO personne VALUES(6,'John','Singleton',1968,"John Singleton est un réalisateur, scénariste et producteur américain, né le 6 janvier 1968 et mort le 28 avril 2019 à Los Angeles.Avec son premier long-métrage, Boyz N the Hood (1991), il est non seulement le plus jeune cinéaste à être nommé à l'Oscar du meilleur réalisateur, mais aussi le premier homme noir à recevoir cette reconnaissance de la part de l'Académie",'../photo/Singleton.png' ,'réalisateur','1');
mysql> INSERT INTO personne VALUES(7,'Rob','Cohen',1949,"Robert Cohen, dit Rob Cohen, est un réalisateur, producteur et scénariste américain, né le 12 mars 1949 à Cornwall (État de New York).",'../photo/Cohen.png','réalisateur','1');
mysql> INSERT INTO personne VALUES(8,'Justin','Lin',1971,"Justin Lin (chinois traditionnel : 林詣彬, chinois simplifié : 林诣彬, pinyin : Lín Yìbīn), né le 11 octobre 1971 à Taipei, est un réalisateur, scénariste producteur, américano-taïwanais.Il a réalisé cinq films de la franchise de films d'action américaine Fast and Furious.",'../photo/Lin.png','réalisateur','3');
mysql> INSERT INTO film VALUES(3,'Fast and Furious 5','../affiche/Fast_and_Furious5.png',"Depuis que Brian O'Conner et Mia Toretto ont extirpé Dominic Toretto des mains de la justice, ils ont dû franchir de nombreuses frontières pour échapper aux autorités. Retirés à Rio, ils sont contraints de monter un dernier coup pour se faire blanchir et retrouver leur liberté. Ils se constituent une équipe d'élite, réunissant les pilotes les plus avertis, conscients que leur seule chance d'être acquittés pour bonne conduite nécessite une confrontation avec l'homme d'affaires véreux, Hernan Reyes, qui souhaite les voir morts. Mais il n'est pas le seul à leurs trousses. L'impitoyable agent fédéral Luke Hobbs n'a jamais manqué ses cibles. Affecté à la traque des fugitifs, lui et son équipe de choc élaborent un implacable dispositif d'assaut destiné à les capturer. Passant le Brésil au crible, Luke réalise combien la frontière qui sépare les bons des méchants est ténue. Il doit alors s'en remettre à son instinct pour acculer ses proies et éviter qu'un autre ne les débusque avant lui.",'Action','8','3,4,5',2011,false,'02:11:00');
mysql> INSERT INTO personne VALUES(9,'David','Fincher',1962,"David Fincher, né le 28 août 1962 à Denver, est un réalisateur et producteur américain reconnu pour ses thrillers psychologiques et drames biographiques. Il a reçu quarante nominations aux Oscars, dont trois pour le meilleur réalisateur.Il débute avec des clips vidéo pour Madonna, remportant des MTV Video Music Awards. Son premier film, Alien 3 (1992), reçoit des critiques mitigées, mais il connaît le succès avec Seven (1995). The Game (1997) et Fight Club (1999) ont un accueil varié, ce dernier devenant culte. Panic Room (2002) marque son retour en force.Il réalise ensuite Zodiac (2007), The Social Network (2010), Millénium (2011), et Mank (2020). The Social Network lui vaut des Golden Globe et BAFTA pour la meilleure réalisation. Ses plus grands succès commerciaux sont L'Étrange Histoire de Benjamin Button (2008) et Gone Girl (2014), chacun rapportant plus de 300 millions de dollars.",'../photo/Fincher.png','réalisateur','4');
mysql> INSERT INTO personne VALUES(10,'Brad','Pitt',1963,"William Bradley Pitt, dit Brad Pitt (prononcé en français [bʁad pit] ; en anglais [bɹæd pɪt]), né le 18 décembre 1963 à Shawnee (Oklahoma), est un acteur et producteur de cinéma américain.À partir de 2002, il s'investit dans la production via sa société Plan B Entertainment avec des films tels que Les Infiltrés de Martin Scorsese et Twelve Years a Slave de Steve McQueen, qui sont chacun récompensés par l'Oscar du meilleur film en 2007 et 2014, The Tree of Life de Terrence Malick, qui reçoit la Palme d'or au Festival de Cannes 2011 ou encore Blonde de Andrew Dominik.Après 3 nominations à l'oscar en tant qu'acteur, il remporte en 2020, celui du meilleur acteur dans un second rôle pour le film Once Upon a Time... in Hollywood de Quentin Tarantino. Il est, avec George Clooney, l’un des deux seuls acteurs à avoir remporté les Oscars du meilleur acteur dans un second rôle et du meilleur film.",'../photo/Pitt.png' ,'acteur','4');
mysql> INSERT INTO personne VALUES(11,'Morgan','Freeman',1937,"Morgan Freeman, né le 1er juin 1937 à Memphis, est un acteur, réalisateur et producteur américain. Débutant sa carrière en 1966, il obtient une reconnaissance internationale avec Miss Daisy et son chauffeur (1989) et Les Évadés (1994). Il remporte l'Oscar du meilleur acteur dans un second rôle pour Million Dollar Baby (2004) et reçoit une nomination pour Invictus (2009).Freeman participe à de nombreuses productions à succès, comme Glory (1989), Robin des Bois, prince des voleurs (1991), Seven (1995), Deep Impact (1998), et la trilogie The Dark Knight (2005, 2008, 2012). Il réalise son premier film, Bopha ! (1993). Très populaire, ses films ont rapporté plus de 4,5 milliards de dollars au box-office mondial",'../photo/Freeman.png','act_réal','4');
mysql> INSERT INTO film VALUES(4,'Seven','../affiche/Seven.png',"Seven est un thriller psychologique réalisé par David Fincher, sorti en 1995. Les inspecteurs David Mills (Brad Pitt) et William Somerset (Morgan Freeman) traquent un tueur en série qui utilise les sept péchés capitaux comme motif de ses meurtres. Chaque crime reflète un péché spécifique, et les meurtres sont orchestrés avec une précision macabre. L'enquête plonge les détectives dans les recoins les plus sombres de la nature humaine, menant à une conclusion choquante et dévastatrice. Le film explore les thèmes de la moralité, de la justice et du mal, tout en maintenant une atmosphère oppressante et intense. Seven a été acclamé pour son scénario, sa réalisation, et les performances de ses acteurs, devenant un classique du genre",'Thriller','9','10,11',1995,false,'02:10:00');
mysql> INSERT INTO personne VALUES(12,'Leonardo','DiCaprio',1974,"Leonardo DiCaprio, né le 11 novembre 1974 à Los Angeles, est un acteur, producteur, scénariste et documentariste américain. Inspiré par son demi-frère Adam Farrar, il commence sa carrière d'acteur dès l'enfance. Il se fait remarquer dans Blessures secrètes (1993) et reçoit une nomination aux Oscars pour Gilbert Grape.Il devient mondialement célèbre avec Roméo + Juliette (1996) et Titanic (1997). DiCaprio collabore souvent avec Martin Scorsese, jouant dans Gangs of New York, Aviator, Les Infiltrés, Shutter Island et Le Loup de Wall Street. Il remporte son premier Oscar du meilleur acteur en 2016 pour The Revenant.",'../photo/Dicaprio.png','acteur','5');
mysql> INSERT INTO personne VALUES(13,'Kate','Winslet',1975,"Kate Winslet, née le 5 octobre 1975 à Reading, Angleterre, est une actrice et productrice britannique. Elle débute à la télévision en 1991 avec Dark Season et au cinéma en 1994 avec Créatures célestes. Elle gagne en reconnaissance avec Raison et Sentiments et atteint la consécration internationale en jouant Rose Dewitt-Bukater dans Titanic (1997).Depuis 2000, Winslet reçoit de nombreux éloges pour ses rôles dans Quills, Iris, Eternal Sunshine of the Spotless Mind, Neverland, Little Children, The Reader, et Les Noces rebelles. Elle est la plus jeune actrice à cumuler six nominations aux Oscars, remportant l'Oscar de la meilleure actrice pour The Reader en 2009.Winslet est également récompensée par des Screen Actors Guild Awards, BAFTA, Golden Globes, et un César d'honneur en 2012. À la télévision, elle remporte un Emmy pour Mildred Pierce et en 2021, un Emmy et un Golden Globe pour Mare of Easttown, où elle fait ses débuts de productrice.",'../photo/Winslet.png','acteur','5');
mysql> INSERT INTO personne VALUES(14,'James','Cameron',1954,"James Cameron, né le 16 août 1954 à Kapuskasing (Canada), est un réalisateur, scénariste, producteur et explorateur de fonds marins canadien résidant en Nouvelle-Zélande. Il est connu pour ses films Terminator (1984), Aliens, le retour (1986), Abyss (1989), Terminator 2 (1991), True Lies (1994), Titanic (1997), Avatar (2009) et Avatar : La Voie de l'eau (2022).En 1997, Titanic devient le plus gros succès du box-office mondial, remportant onze Oscars, dont ceux du meilleur film et du meilleur réalisateur pour Cameron. En 2009, il bat ce record avec Avatar, un film de science-fiction au budget estimé à 400 millions de dollars, qui génère 2,78 milliards de dollars de recettes.Cameron possède sa société de production, Lightstorm Entertainment, et a cofondé la société d'effets spéciaux Digital Domain. Il a une étoile sur l'Allée des célébrités canadiennes depuis 2008 et sur le Hollywood Walk of Fame depuis 2009.",'../photo/Cameron.png','réalisateur','5');
mysql> INSERT INTO film VALUES(5,'Titanic','../affiche/Titanic.png',"Titanic est un film réalisé par James Cameron, sorti en 1997. Il raconte l'histoire de Jack Dawson (Leonardo DiCaprio) et Rose DeWitt Bukater (Kate Winslet), deux jeunes gens de classes sociales différentes, qui se rencontrent et tombent amoureux à bord du Titanic, le célèbre paquebot réputé insubmersible. Leur romance naît malgré les obstacles et les pressions sociales, mais est brutalement interrompue par le naufrage tragique du navire après sa collision avec un iceberg. Le film mêle histoire d'amour et drame historique, tout en rendant hommage aux victimes de la catastrophe.",'Drame','14','12,13',1997,false,'03:14:00');
mysql> INSERT INTO personne VALUES(15,'Tom','Hanks',1956,"Tom Hanks, né le 9 juillet 1956 à Concord (Californie), est un acteur, réalisateur et producteur américano-grec. Devenu citoyen grec en 2020 avec sa femme Rita Wilson, il se fait connaître avec Splash et remporte deux Oscars pour Philadelphia et Forrest Gump. Il joue dans des succès comme Apollo 13, Il faut sauver le soldat Ryan, Toy Story et La Ligne verte.En 2012, ses films ont généré plus de 4,2 milliards de dollars aux États-Unis et 8,5 milliards dans le monde. En 2006, Forbes le classe parmi les célébrités les mieux payées avec 29 millions de dollars. Il reçoit la Légion d’honneur en 2016 et la médaille présidentielle de la Liberté la même année. En 2020, il est considéré comme une personnalité influente pour l'élection présidentielle américaine",'../photo/Hanks.png','act_réal','6');
mysql> INSERT INTO personne VALUES(16,'Michael Clarke','Duncan',1957,"Michael Clarke Duncan, né le 10 décembre 1957 à Chicago et mort le 3 septembre 2012 à Los Angeles, est un acteur américain. Connu pour sa stature imposante (1,96 m, 142 kg), il débute comme agent de sécurité et garde du corps pour des célébrités.Il se tourne vers Hollywood, obtenant des rôles dans des publicités et des films comme Armageddon (1998). En 1999, son rôle dans La Ligne verte lui vaut des nominations aux Oscars et aux Golden Globes. Il joue ensuite dans des blockbusters tels que La Planète des singes, Le Roi Scorpion, Daredevil, Sin City, et Green Lantern. Il prête aussi sa voix dans Frère des ours et Kung Fu Panda.",'../photo/Duncan.png','acteur','6');
mysql> INSERT INTO personne VALUES(17,'Frank','Darabont',1959,"Ferenc Árpád Darabont dit Frank Darabont, né le 28 janvier 1959 à Montbéliard (France), est un réalisateur, scénariste, producteur compositeur, musicien et acteur de cinéma américain d'origine hongroise. Il s'est surtout illustré en réalisant trois longs métrages adaptés d'œuvres de Stephen King : Les Évadés (1994), La Ligne verte (1999), et The Mist (2007). Il est par ailleurs à l'origine du développement des séries télévisées The Walking Dead et Mob City et travaille régulièrement comme script doctor sur des scénarios de films",'../photo/Darabont.png','réalisateur','6');
mysql> INSERT INTO film VALUES(6,'La Ligne verte','../affiche/Ligne_verte.png',"La Ligne verte est un film dramatique de 1999 réalisé par Frank Darabont, adapté du roman de Stephen King. L'histoire se déroule en 1935 dans une prison de Louisiane, où Paul Edgecomb (Tom Hanks) est le gardien en chef du bloc des condamnés à mort, surnommé 'la Ligne verte' en raison de la couleur du sol. Paul et son équipe rencontrent John Coffey (Michael Clarke Duncan), un détenu gigantesque condamné pour le meurtre de deux fillettes.Malgré son apparence intimidante, Coffey est doux, sensible et semble posséder des pouvoirs surnaturels de guérison. Au fur et à mesure que Paul découvre les capacités extraordinaires de Coffey, il commence à douter de sa culpabilité. Le film explore des thèmes profonds de justice, de compassion et de spiritualité, tout en offrant une réflexion poignante sur la nature humaine et la peine de mort.La performance de Michael Clarke Duncan en tant que John Coffey a été largement acclamée, lui valant des nominations aux Oscars et aux Golden Globes.",'Drame','17','15,16',1999,false,'03:09:00');
